# Generated by Django 5.1.6 on 2025-02-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_todo_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
