# Generated by Django 5.1.6 on 2025-02-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_alter_todo_complete_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='todo',
            name='complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
