# Generated by Django 5.1.6 on 2025-02-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_todo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cususer',
            name='role',
            field=models.CharField(choices=[('USER_ROLE_ADMIN', 'Admin user'), ('USER_ROLE_REGULAR', 'Regular user')], default='USER_ROLE_ADMIN', max_length=100),
        ),
    ]
