# Generated by Django 5.1.6 on 2025-02-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0009_alter_cususer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cususer',
            name='role',
            field=models.CharField(choices=[('USER_ROLE_REGULAR', 'Regular user'), ('USER_ROLE_ADMIN', 'Admin user')], default='USER_ROLE_ADMIN', max_length=100),
        ),
    ]
