name: Workflows

on:
  push:
    branches: [ workflows ]

  pull_request:
    branches: [ main ]

jobs:
  build_and_run:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout code
        user: actions/checkout@v3

      - name: Setup Python
        user: actions/setup-python@4
        with: 
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
      
      - name: Run tests
        run: |
          poetry run pytest

          poetry run flake8

      


